Update build.yml
Signed-off-by: a02-trial <cipin23@gmail.com>

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -22,20 +22,75 @@ on:
 jobs:
   build:
     name: Build Kernel by ${{ github.actor }}
-    runs-on: ubuntu-24.04
+    runs-on: ubuntu-20.04
+    if: github.event.repository.owner.id == github.event.sender.id
+    permissions:
+      contents: write
     steps:
-    - name: "Checkout kernel source"                  # Clone the kernel source.
+    # This action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
+    - name: Checkout
       uses: actions/checkout@v4
-    - name: "Checkout zipper"                         # (OPTIONAL) Clone the AnyKernel3 template.
-      uses: actions/checkout@v4
+    # Install necessary packages for building android kernel
+    - name: Cleanup
+      uses: rokibhasansagar/slimhub_actions@main
+      
+    - name: Set Swap Space
+      uses: pierotofy/set-swap-space@master
       with:
-        repository: lemniskett/AnyKernel3             # Your own AnyKernel3 repository.
-        path: zipper                                  # Clone to path "zipper", REQUIRED.
-    - name: "Android kernel build"                    # Build kernel with lemniskett/android-kernel-actions.
-      uses: lemniskett/android-kernel-actions@master
-      with:
-        arch: arm                                     # Specify arch
-        compiler: gcc/9                               # Specify toolchain to use
-        defconfig: a02_defconfig                      # Specify defconfig to use
-        image: Image                                  # Specify final build file
+        swap-size-gb: 32
+    # Install repo tool in case it was not yet installed
 
+    - name: Build Environment
+      run: |
+        sudo apt update -y
+        sudo apt install bison flex rsync bison device-tree-compiler bc -y
+        
+    - name: Install Repo Tool
+      run: |
+        git config --global color.ui false
+        if ! command -v repo &> /dev/null; then
+            echo "'repo' command not found. Installing..."
+            mkdir -p ~/bin  # Create bin directory if it doesn't exist
+            curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
+            chmod a+x ~/bin/repo
+            sudo ln -sf ~/bin/repo /usr/bin/repo
+            echo "'repo' command installed successfully."
+        else
+            echo "'repo' command already exists."
+        fi
+    # Initial the kernel manifest then sync after
+    - name: Initialize Manifest and Sync
+      run: |
+        mkdir -p android
+        cd android
+        git config --global user.name "${{ github.actor }}"
+        git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
+        repo init --depth=1 -u ${{ inputs.MANIFEST_URL }} -b ${{ inputs.MANIFEST_BRANCH }}
+        repo sync
+    # Starts the compiling process of android kernel
+    - name: Build Kernel
+      run: |
+        cd android
+        BUILD_CONFIG="${{ inputs.BUILD_CONFIG }}" build/build.sh 2>&1 | tee build.log
+    # Check if the out directory consist of target kernel image
+    - name: Setup kernel
+      continue-on-error: true
+      run: |
+        mkdir -p android/kernelbuild
+        mkdir -p android/modulebuild
+        cp -nf $(find android -name '${{ inputs.KERNEL_IMAGE_NAME }}') android/kernelbuild/ 2>/dev/null
+        cp -nf $(find android -name '${{ inputs.KERNEL_IMAGE_NAME }}.gz') android/kernelbuild/ 2>/dev/null
+        cp -nf $(find android -name '${{ inputs.KERNEL_IMAGE_NAME }}.lz4') android/kernelbuild/ 2>/dev/null
+    # Upload the release, if build is successful
+    - name: Upload to Release
+      uses: softprops/action-gh-release@v1
+      with:
+        files: |
+          android/kernelbuild/${{ inputs.KERNEL_IMAGE_NAME }}
+          android/kernelbuild/${{ inputs.KERNEL_IMAGE_NAME }}.gz
+          android/kernelbuild/${{ inputs.KERNEL_IMAGE_NAME }}.lz4
+        name: Android Kernel Release | ${{ github.run_id }}
+        tag_name: ${{ github.run_id }}
+        body: |
+          ## Build Information
+          Manifest: ${{ inputs.MANIFEST_URL }}/tree/${{ inputs.MANIFEST_BRANCH }}
